events {}

http {

    resolver 127.0.0.11 valid=10s;

    upstream metro_backend {
        zone metro_backend 64k;

        server metro-app:8080 resolve;
    }

    server {

        listen 80;

        location / {
            proxy_pass http://metro_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}