spring.application.name=metro
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#spring.datasource.url=jdbc:postgresql://postgres:5432/metro_db
#spring.datasource.username=postgres
#spring.datasource.password=12345678

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

management.endpoints.web.exposure.include=health